# -*- coding: utf-8 -*-
# Auto-generated by mirai. Do not edit manually.

import os
import tensorflow as tf
from tensorflow.python.framework.load_library import load_op_library

fwd_op_name = '{{ fwd_op_name }}'
bwd_op_name = '{{ bwd_op_name }}'


def init_{{ op_name | lower }}(ops_dir, fwd_version="tf32", bwd_version="tf32"):
    fwd_op = load_op_library(os.path.join(ops_dir, fwd_op_name + '.so'))
    bwd_op = load_op_library(os.path.join(ops_dir, bwd_op_name + '.so'))

    @tf.custom_gradient
    def fused_{{ op_name | lower }}({{ user_param_names | join(', ') }}):
        fwd_prefix = os.path.join(ops_dir, fwd_version, fwd_op_name) + '/'
        outputs = fwd_op.{{ fwd_op_name }}(
            {% for user_name, internal_name in fwd_param_mapping -%}
            {{ internal_name }}={{ user_name }},
            {% endfor -%}
            asset_prefix=fwd_prefix
        )
        {{ fwd_output_names | join(', ') }} = outputs

        def grad(d_output):
            bwd_prefix = os.path.join(ops_dir, bwd_version, bwd_op_name) + '/'
            {{ bwd_output_names | join(', ') }} = bwd_op.{{ bwd_op_name }}(
                {% for bwd_input_name, fwd_source_name in bwd_param_mapping -%}
                {{ bwd_input_name }}={{ fwd_source_name }},
                {% endfor -%}
                {{ tangent_name }}=d_output,
                asset_prefix=bwd_prefix
            )
            return {{ bwd_output_names | join(', ') }}

        return {{ fwd_result_name }}, grad

    return fused_{{ op_name | lower }}
